routes/web.php
<?php

use App\Http\Controllers\Dashboard;
use App\Http\Controllers\Home;
use Illuminate\Support\Facades\Route;

Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');

Route::resource('/modules/dosen/riwayat-pendidikan',App\Http\Controllers\RiwayatPendidikanController::class)
->except(['index', 'create', 'store', 'show']);

Route::resource('/modules/dosen/mata-kuliah', \App\Http\Controllers\DosenMatkulController::class);

Route::prefix('modules/mahasiswa')->name('mahasiswa.')->group(function () {
    Route::resource('mata-kuliah', \App\Http\Controllers\MahasiswaMatkulController::class);
});

app/Models/RiwayatPendidikan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Modules\Dosen\Models\Dosen;

class RiwayatPendidikan extends Model
{
    use HasFactory;

    protected $table = 'riwayat_pendidikan';

    protected $guarded = [];

    public function dosen() {
        return $this->belongsTo(Dosen::class, 'dosen_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Notifications\Notifiable;
use Laravolt\Support\Traits\AutoFilter;
use Laravolt\Support\Traits\AutoSort;

class User extends \Laravolt\Platform\Models\User
{
    use HasFactory;
    use Notifiable;
    use AutoSort;
    use AutoFilter;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $fillable = ['name', 'email', 'username', 'password', 'status', 'timezone'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Dashboard.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Dashboard extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        return view('dashboard');
    }
}

app/Http/Controllers/DosenMatkulController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Modules\Dosen\Models\Dosen;
use Modules\Mkuliah\Models\Mkuliah;

class DosenMatkulController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View|Response
     */
    public function show($id)
    {
        $dosen = Dosen::with('mata_kuliah')->find($id);
        $matkul = Mkuliah::all();
        $sks = $dosen->mata_kuliah->sum('jumlah_sks');

        return view('dosen-matkul.show', compact('dosen', 'matkul', 'sks'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $dosen = Dosen::find($id);
        $dosen->mata_kuliah()->sync($request->matkul);

        return redirect()->back()->withSuccess('Mata Kuliah updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Home.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Home extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        return redirect()->route('auth::login');
    }
}

app/Http/Controllers/MahasiswaMatkulController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Modules\Mahasiswa\Models\Mahasiswa;
use Modules\Mkuliah\Models\Mkuliah;

class MahasiswaMatkulController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View|Response
     */
    public function edit($id)
    {
        $mahasiswa = Mahasiswa::find($id);
        $matkul = Mkuliah::all();
        $sks = $mahasiswa->mata_kuliah->sum('jumlah_sks');

        return view('mahasiswa-matkul.edit', compact('mahasiswa', 'matkul', 'sks'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $mahasiswa = Mahasiswa::find($id);
        $mahasiswa->mata_kuliah()->sync($request->matkul);

        if ($mahasiswa->mata_kuliah->sum('jumlah_sks') > 24) {
            $mahasiswa->mata_kuliah()->detach();
            return back()->withErrors('Jumlah SKS tidak boleh lebih dari 24!');
        } else {
            return redirect()->back()->withSuccess('Mata Kuliah updated');
        }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/RiwayatPendidikanController.php
<?php

namespace App\Http\Controllers;

use App\Models\RiwayatPendidikan;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Modules\Dosen\Models\Dosen;

class RiwayatPendidikanController extends Controller
{
    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View|Response
     */
    public function edit(RiwayatPendidikan $riwayatPendidikan)
    {
        return view('riwayat-pendidikan.edit', compact('riwayatPendidikan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, RiwayatPendidikan $riwayatPendidikan)
    {
        $riwayatPendidikan->update($request->all());

        return redirect()->back()->withSuccess('Riwayat Pendidikan updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy(RiwayatPendidikan $riwayatPendidikan)
    {
        $riwayatPendidikan->delete();

        return redirect()->back()->withSuccess('Riwayat pendidikan deleted');
    }
}

resources/views/dashboard.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <div style="display: flex; min-height: 600px; align-items: center; justify-content: center; flex-direction: column">
        <h1 class="ui header" style="font-size: 5em; font-weight: 100; letter-spacing: .15em">
            Your Awesome Dashboard
        </h1>

        <div>
            Check file <code class="ui label">{{ \App\Http\Controllers\Dashboard::class }}</code> to edit this page.
        </div>

    </div>
@endsection

resources/views/dosen-matkul/show.blade.php
@extends('laravolt::layouts.app')
@section('content')

    <x-backlink url="{{ route('modules::dosen.index') }}"></x-backlink>

    <x-panel title="Dosen">
        <table class="ui table definition">
            <tbody>
            <tr>
                <td>Nama</td>
                <td>{{ $dosen->name }}</td>
            </tr>
            <tr>
                <td>NIP</td>
                <td>{{ $dosen->nip }}</td>
            </tr>
            <tr>
                <td>Gelar</td>
                <td>{{ $dosen->gelar }}</td>
            </tr>
            </tbody>
        </table>
    </x-panel>

    <x-panel title="Mata Kuliah yang Diampu">
        {!! form()->bind($dosen)->open()->put()->action(route('mata-kuliah.update', $dosen->id)) !!}

        @foreach($matkul as $item)
            <label>
                <input type="checkbox" class="ui checkbox p-b-2" name="matkul[]" value="{{ $item->id }}"
                    {{ $dosen->mata_kuliah->contains($item->id)  ? 'checked' : ''  }}>
                <strong>{{ $item->name }}</strong>{{ ' - ' . $item->jumlah_sks . ' SKS' }}
            </label>
            <br>
        @endforeach
        <br>
        Jumlah SKS dari mata kuliah yang diampu: {{ $sks }}

        <div class="ui divider hidden"></div>

        {!!
            form()->action([
                form()->submit('Save'),
                form()->link('Kembali', route('modules::dosen.index'))
            ])
        !!}
        {!! form()->close() !!}
    </x-panel>
@stop

resources/views/mahasiswa-matkul/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-backlink url="{{ route('modules::mahasiswa.index') }}"></x-backlink>

    <x-panel title="Mahasiswa">
        <table class="ui table definition">
            <tr>
                <td>Name</td>
                <td>{{ $mahasiswa->name }}</td>
            </tr>
            <tr>
                <td>NIM</td>
                <td>{{ $mahasiswa->nim }}</td>
            </tr>
            <tr>
                <td>Gender</td>
                <td>{{ ucfirst($mahasiswa->gender) }}</td>
            </tr>
            <tr>
                <td>Tempat dan Tanggal Lahir</td>
                <td>{{ $mahasiswa->tempat_lahir . ', ' . date('d F Y', strtotime($mahasiswa->tanggal_lahir)) }}</td>
            </tr>
        </table>
    </x-panel>

    <x-panel title="Mata Kuliah yang Diambil">
        {!! form()->bind($mahasiswa)->put(route('mahasiswa.mata-kuliah.update', $mahasiswa->id))!!}

        @foreach($matkul as $item)
            <label>
                <input type="checkbox" class="ui checkbox p-b-2" name="matkul[]" value="{{ $item->id }}"
                    {{ $mahasiswa->mata_kuliah->contains($item->id)  ? 'checked' : ''  }}>
                <strong>{{ $item->name }}</strong>{{ ' - ' . $item->jumlah_sks . ' SKS' }}
            </label>
            <br>
        @endforeach
        <br>
        Jumlah SKS dari mata kuliah yang diambil: {{ $sks }}

        <div class="ui divider hidden"></div>

        {!!
            form()->action([
                form()->submit('Save'),
                form()->link('Kembali', route('modules::mahasiswa.index'))
            ])
        !!}
        {!! form()->close() !!}
    </x-panel>

@stop

resources/views/riwayat-pendidikan/edit.blade.php
@extends('laravolt::layouts.app')
@section('content')
    <x-backlink url="{{ route('modules::dosen.edit', $riwayatPendidikan->dosen->id) }}"></x-backlink>

    <x-panel title="Edit Riwayat Pendidikan Milik {{ $riwayatPendidikan->dosen->name }}">
        {!! form()->bind($riwayatPendidikan)->put(route('riwayat-pendidikan.update', $riwayatPendidikan->getKey()))->horizontal()!!}
        {!! form()->text('strata', $riwayatPendidikan->strata)->label('Strata') !!}
        {!! form()->text('jurusan', $riwayatPendidikan->jurusan)->label('Jurusan') !!}
        {!! form()->text('sekolah', $riwayatPendidikan->sekolah)->label('Sekolah') !!}

        {!! form()->datepicker('tahun_mulai', $riwayatPendidikan->tahun_mulai)->label('Tahun Mulai') !!}
        {!! form()->datepicker('tahun_selesai', $riwayatPendidikan->tahun_selesai)->label('Tahun Selesai') !!}

        {!!
            form()->action([
                form()->submit('Save'),
                form()->link('Kembali', route('modules::dosen.edit', $riwayatPendidikan->dosen->id))
            ])
        !!}
        {!! form()->close() !!}
    </x-panel>
@endsection